attachments_folder: attachments
batch_size: 10
database_properties:
  Created:
    type: created_time
  Modified:
    type: last_edited_time
  Name:
    type: title
  Source File:
    type: rich_text
  Tags:
    type: multi_select
dry_run: false
extract_frontmatter: true
max_file_size: 20971520
max_workers: 3
notion_token: YOUR_NOTION_TOKEN_HERE
source_vault_path: /path/to/your/obsidian/vault
target_database_id: YOUR_TARGET_DATABASE_ID_HERE
